<a href="https://colab.research.google.com/github/RajeshJoshi8848/Github/blob/main/movieprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

Import Dataset

In [3]:
df=pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Movies%20Recommendation.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Movie_ID                  4760 non-null   int64
 1   Movie_Title               4760 non-null   object
 2   Movie_Genre               4760 non-null   object
 3   Movie_Language            4760 non-null   object
 4   Movie_Budget              4760 non-null   int64
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object
 7   Movie_Revenue             4760 non-null   int64
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64
 11  Movie_Homepage            1699 non-null   object
 12  Movie_Keywords            4373 non-null   object
 13  Movie_Overview            4757 non-null   object
 14  Movie_Production_House    4760 non-null   object
 15  Movie_Production_Country  4760 non-null   object
 16  Movie_Spoken_Language     4760 non-null   object
 17  Movie_Tagline             3942 non-null   object
 18  Movie_Cast                4733 non-null   object
 19  Movie_Crew                4760 non-null   object
 20  Movie_Director            4738 non-null   object
dtypes: float64(3), int64(4), object(14)
memory usage: 781.1+ KB

In [5]:
df.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [6]:
df.describe()

,Movie_ID,Movie_Budget,Movie_Popularity,Movie_Revenue,Movie_Runtime,Movie_Vote,Movie_Vote_Count
count,4760.000000,4.760000e+03,4760.000000,4.760000e+03,4758.000000,4760.000000,4760.000000
mean,2382.566387,2.920129e+07,21.599510,8.263743e+07,107.184111,6.113866,692.508403
std,1377.270159,4.075620e+07,31.887919,1.630554e+08,21.960332,1.141294,1235.007337
min,1.000000,0.000000e+00,0.000372,0.000000e+00,0.000000,0.000000,0.000000
25%,1190.750000,9.257500e+05,4.807074,0.000000e+00,94.000000,5.600000,55.000000
50%,2380.500000,1.500000e+07,13.119058,1.944716e+07,104.000000,6.200000,238.000000
75%,3572.250000,4.000000e+07,28.411929,9.341276e+07,118.000000,6.800000,740.250000
max,4788.000000,3.800000e+08,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
df.shape

(4760, 21)

In [8]:
df.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

Feature Selection

In [9]:
df_feature=df[['Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity']].fillna('')

In [10]:
df_feature.shape

(4760, 5)

In [11]:
df_feature

,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity
0,Four Rooms,Crime Comedy,en,4000000,22.876230
1,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695
2,Finding Nemo,Animation Family,en,94000000,85.688789
3,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331
4,American Beauty,Drama,en,15000000,80.878605
...,...,...,...,...,...
4755,Midnight Cabaret,Horror,en,0,0.001389
4756,Growing Up Smith,Comedy Family Drama,en,0,0.710870
4757,8 Days,Thriller Drama,en,0,0.015295
4758,Running Forever,Family,en,0,0.028756
4759,"To Be Frank, Sinatra at 100",Documentary,en,2,0.050625

In [12]:
x = df_feature['Movie_Title'].astype(str) + '' + \
    df_feature['Movie_Genre'].astype(str) + '' + \
    df_feature['Movie_Language'].astype(str) + '' + \
    df_feature['Movie_Budget'].astype(str) + '' + \
    df_feature['Movie_Popularity'].astype(str)

In [13]:
x

0                 Four RoomsCrime Comedyen400000022.87623
1       Star WarsAdventure Action Science Fictionen110...
2         Finding NemoAnimation Familyen9400000085.688789
3       Forrest GumpComedy Drama Romanceen55000000138....
4                 American BeautyDramaen1500000080.878605
                              ...
4755                    Midnight CabaretHorroren00.001389
4756        Growing Up SmithComedy Family Dramaen00.71087
4757                      8 DaysThriller Dramaen00.015295
4758                     Running ForeverFamilyen00.028756
4759    To Be Frank, Sinatra at 100Documentaryen20.050625
Length: 4760, dtype: object

In [14]:
x.shape

(4760,)

  Get feature text conversion to tokens

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer()

In [17]:
x= tfidf.fit_transform(x)

In [18]:
x.shape

(4760, 14700)

In [19]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 25439 stored elements and shape (4760, 14700)>
  Coords	Values
  (0, 8634)	0.42644119731598773
  (0, 12237)	0.5222221446956926
  (0, 6338)	0.5222221446956926
  (0, 4313)	0.5222221446956926
  (1, 12785)	0.377397801891299
  (1, 14351)	0.5076341608300441
  (1, 4907)	0.21403732052420651
  (1, 12369)	0.1966763860395162
  (1, 8251)	0.5076341608300441
  (1, 2058)	0.5076341608300441
  (2, 8502)	0.46949608686962174
  (2, 10882)	0.5097625016986219
  (2, 8027)	0.5097625016986219
  (2, 3412)	0.5097625016986219
  (3, 8622)	0.4930801995571393
  (3, 8980)	0.4930801995571393
  (3, 7171)	0.1657940506133042
  (3, 12075)	0.4930801995571393
  (3, 727)	0.4930801995571393
  (4, 5216)	0.4453348480881793
  (4, 5541)	0.6331180273370354
  (4, 4329)	0.6331180273370354
  (5, 6846)	0.4515274701322038
  (5, 9553)	0.25434686608861484
  (5, 13104)	0.12036742815940751
  :	:
  (4754, 5729)	0.4511936259605387
  (4754, 8068)	0.4511936259605387
  (4754, 3363)	0.4511936259605387
  (4755, 10413)	0.5115848560532547
  (4755, 5915)	0.6075693108843512
  (4755, 12)	0.6075693108843512
  (4756, 7821)	0.23072506853479596
  (4756, 14061)	0.389205644258067
  (4756, 7175)	0.33730643152933065
  (4756, 8961)	0.4766232895681263
  (4756, 12635)	0.4766232895681263
  (4756, 3527)	0.4766232895681263
  (4757, 7175)	0.44751380497955373
  (4757, 6914)	0.6323493474151459
  (4757, 89)	0.6323493474151459
  (4758, 12286)	0.5350143883724752
  (4758, 8616)	0.5973941765009206
  (4758, 160)	0.5973941765009206
  (4759, 13833)	0.2351793683343266
  (4759, 5380)	0.310910914388031
  (4759, 5518)	0.34046230168139774
  (4759, 8643)	0.42781727675436115
  (4759, 12567)	0.42781727675436115
  (4759, 553)	0.42781727675436115
  (4759, 278)	0.42781727675436115

Get similarity Score using Cosine Similarity

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
Similarity_score= cosine_similarity(x)

In [22]:
Similarity_score

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
Similarity_score.shape

(4760, 4760)

Get movie name as Input from user and Validate for Closest Spelling

In [24]:
Favourite_movie_name = input('Enter your favourite movie name: ')

Enter your favourite movie name: Avengers

In [25]:
All_movie_title_list = df['Movie_Title'].tolist()

In [26]:
import difflib

In [27]:
Movie_Recommandation= difflib.get_close_matches(Favourite_movie_name, All_movie_title_list)
print(Movie_Recommandation)

['The Avengers', 'Swingers']

In [28]:
Close_Match= Movie_Recommandation[0]
print(Close_Match)

The Avengers

In [29]:
Index_of_Close_Match_Movie= df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

2851

Getting list of similar movies

In [30]:
Recommendation_Score= list(enumerate(Similarity_score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

[(0, np.float64(0.0)), (1, np.float64(0.0)), (2, np.float64(0.0)), (3, np.float64(0.0)), (4, np.float64(0.0)), (5, np.float64(0.0)), (6, np.float64(0.0)), (7, np.float64(0.0)), (8, np.float64(0.0)), (9, np.float64(0.0)), (10, np.float64(0.0)), (11, np.float64(0.0)), (12, np.float64(0.0)), (13, np.float64(0.0)), (14, np.float64(0.0)), (15, np.float64(0.0)), (16, np.float64(0.0)), (17, np.float64(0.0)), (18, np.float64(0.0)), (19, np.float64(0.0)), (20, np.float64(0.0)), (21, np.float64(0.0)), (22, np.float64(0.0)), (23, np.float64(0.0)), (24, np.float64(0.0)), (25, np.float64(0.0)), (26, np.float64(0.0)), (27, np.float64(0.0)), (28, np.float64(0.0)), (29, np.float64(0.0)), (30, np.float64(0.0)), (31, np.float64(0.0)), (32, np.float64(0.0)), (33, np.float64(0.0)), (34, np.float64(0.0)), (35, np.float64(0.0)), (36, np.float64(0.0)), (37, np.float64(0.0)), (38, np.float64(0.0)), (39, np.float64(0.0)), (40, np.float64(0.0)), (41, np.float64(0.0)), (42, np.float64(0.0)), (43, np.float64(0.0)), (44, np.float64(0.0)), (45, np.float64(0.0)), (46, np.float64(0.0)), (47, np.float64(0.0)), (48, np.float64(0.0)), (49, np.float64(0.0)), (50, np.float64(0.0)), (51, np.float64(0.0)), (52, np.float64(0.0)), (53, np.float64(0.0)), (54, np.float64(0.0)), (55, np.float64(0.0)), (56, np.float64(0.0)), (57, np.float64(0.0)), (58, np.float64(0.0)), (59, np.float64(0.0)), (60, np.float64(0.0)), (61, np.float64(0.0)), (62, np.float64(0.0)), (63, np.float64(0.0)), (64, np.float64(0.0)), (65, np.float64(0.0)), (66, np.float64(0.0)), (67, np.float64(0.0)), (68, np.float64(0.0)), (69, np.float64(0.0)), (70, np.float64(0.0)), (71, np.float64(0.0)), (72, np.float64(0.0)), (73, np.float64(0.0)), (74, np.float64(0.0)), (75, np.float64(0.0)), (76, np.float64(0.0)), (77, np.float64(0.0)), (78, np.float64(0.0)), (79, np.float64(0.0)), (80, np.float64(0.0)), (81, np.float64(0.0)), (82, np.float64(0.0)), (83, np.float64(0.0)), (84, np.float64(0.0)), (85, np.float64(0.0)), (86, np.float64(0.0)), (87, np.float64(0.0)), (88, np.float64(0.0)), (89, np.float64(0.0)), (90, np.float64(0.0)), (91, np.float64(0.0)), (92, np.float64(0.0)), (93, np.float64(0.0)), (94, np.float64(0.0)), (95, np.float64(0.0)), (96, np.float64(0.0)), (97, np.float64(0.0)), (98, np.float64(0.0)), (99, np.float64(0.0)), (100, np.float64(0.0)), (101, np.float64(0.0)), (102, np.float64(0.0)), (103, np.float64(0.0)), (104, np.float64(0.0)), (105, np.float64(0.0)), (106, np.float64(0.0)), (107, np.float64(0.0)), (108, np.float64(0.0)), (109, np.float64(0.0)), (110, np.float64(0.0)), (111, np.float64(0.0)), (112, np.float64(0.0)), (113, np.float64(0.0)), (114, np.float64(0.0)), (115, np.float64(0.0)), (116, np.float64(0.0)), (117, np.float64(0.0)), (118, np.float64(0.0)), (119, np.float64(0.0)), (120, np.float64(0.0)), (121, np.float64(0.0)), (122, np.float64(0.0)), (123, np.float64(0.0)), (124, np.float64(0.0)), (125, np.float64(0.0)), (126, np.float64(0.0)), (127, np.float64(0.0)), (128, np.float64(0.0)), (129, np.float64(0.0)), (130, np.float64(0.0)), (131, np.float64(0.0)), (132, np.float64(0.0)), (133, np.float64(0.0)), (134, np.float64(0.0)), (135, np.float64(0.0)), (136, np.float64(0.0)), (137, np.float64(0.0)), (138, np.float64(0.0)), (139, np.float64(0.0)), (140, np.float64(0.0)), (141, np.float64(0.0)), (142, np.float64(0.0)), (143, np.float64(0.0)), (144, np.float64(0.0)), (145, np.float64(0.0)), (146, np.float64(0.0)), (147, np.float64(0.0)), (148, np.float64(0.0)), (149, np.float64(0.0)), (150, np.float64(0.0)), (151, np.float64(0.0)), (152, np.float64(0.0)), (153, np.float64(0.0)), (154, np.float64(0.0)), (155, np.float64(0.0)), (156, np.float64(0.0)), (157, np.float64(0.0)), (158, np.float64(0.0)), (159, np.float64(0.0)), (160, np.float64(0.0)), (161, np.float64(0.0)), (162, np.float64(0.0)), (163, np.float64(0.0)), (164, np.float64(0.0)), (165, np.float64(0.0)), (166, np.float64(0.0)), (167, np.float64(0.0)), (168, np.float64(0.0)), (169, np.float64(0.0)), (170, np.float64(0.0)), (171, np.float64(0.0)), (172, np.float64(0.0)), (173, np.float64(0.0)), (174, np.float64(0.0)), (175, np.float64(0.0)), (176, np.float64(0.0)), (177, np.float64(0.0)), (178, np.float64(0.0)), (179, np.float64(0.0)), (180, np.float64(0.0)), (181, np.float64(0.0)), (182, np.float64(0.0)), (183, np.float64(0.0)), (184, np.float64(0.0)), (185, np.float64(0.0)), (186, np.float64(0.0)), (187, np.float64(0.0)), (188, np.float64(0.0)), (189, np.float64(0.0)), (190, np.float64(0.0)), (191, np.float64(0.0)), (192, np.float64(0.0)), (193, np.float64(0.0)), (194, np.float64(0.0)), (195, np.float64(0.0)), (196, np.float64(0.0)), (197, np.float64(0.0)), (198, np.float64(0.0)), (199, np.float64(0.0)), (200, np.float64(0.0)), (201, np.float64(0.0)), (202, np.float64(0.0)), (203, np.float64(0.0)), (204, np.float64(0.0)), (205, np.float64(0.0)), (206, np.float64(0.0)), (207, np.float64(0.0)), (208, np.float64(0.0)), (209, np.float64(0.0)), (210, np.float64(0.0)), (211, np.float64(0.0)), (212, np.float64(0.0)), (213, np.float64(0.0)), (214, np.float64(0.0)), (215, np.float64(0.0)), (216, np.float64(0.0)), (217, np.float64(0.0)), (218, np.float64(0.0)), (219, np.float64(0.0)), (220, np.float64(0.0)), (221, np.float64(0.0)), (222, np.float64(0.0)), (223, np.float64(0.0)), (224, np.float64(0.0)), (225, np.float64(0.0)), (226, np.float64(0.0)), (227, np.float64(0.0)), (228, np.float64(0.0)), (229, np.float64(0.0)), (230, np.float64(0.0)), (231, np.float64(0.0)), (232, np.float64(0.0)), (233, np.float64(0.0)), (234, np.float64(0.0)), (235, np.float64(0.0)), (236, np.float64(0.0)), (237, np.float64(0.0)), (238, np.float64(0.0)), (239, np.float64(0.0)), (240, np.float64(0.0)), (241, np.float64(0.0)), (242, np.float64(0.0)), (243, np.float64(0.0)), (244, np.float64(0.0)), (245, np.float64(0.0)), (246, np.float64(0.0)), (247, np.float64(0.0)), (248, np.float64(0.0)), (249, np.float64(0.0)), (250, np.float64(0.0)), (251, np.float64(0.0)), (252, np.float64(0.0)), (253, np.float64(0.0)), (254, np.float64(0.0)), (255, np.float64(0.0)), (256, np.float64(0.0)), (257, np.float64(0.0)), (258, np.float64(0.0)), (259, np.float64(0.0)), (260, np.float64(0.0)), (261, np.float64(0.0)), (262, np.float64(0.0)), (263, np.float64(0.0)), (264, np.float64(0.0)), (265, np.float64(0.0)), (266, np.float64(0.0)), (267, np.float64(0.0)), (268, np.float64(0.0)), (269, np.float64(0.0)), (270, np.float64(0.0)), (271, np.float64(0.0)), (272, np.float64(0.0)), (273, np.float64(0.0)), (274, np.float64(0.0)), (275, np.float64(0.0)), (276, np.float64(0.0)), (277, np.float64(0.0)), (278, np.float64(0.0)), (279, np.float64(0.0)), (280, np.float64(0.0)), (281, np.float64(0.0)), (282, np.float64(0.0)), (283, np.float64(0.0)), (284, np.float64(0.0)), (285, np.float64(0.0)), (286, np.float64(0.0)), (287, np.float64(0.0)), (288, np.float64(0.0)), (289, np.float64(0.0)), (290, np.float64(0.0)), (291, np.float64(0.0)), (292, np.float64(0.0)), (293, np.float64(0.0)), (294, np.float64(0.0)), (295, np.float64(0.0)), (296, np.float64(0.0)), (297, np.float64(0.0)), (298, np.float64(0.0)), (299, np.float64(0.0)), (300, np.float64(0.0)), (301, np.float64(0.0)), (302, np.float64(0.0)), (303, np.float64(0.0)), (304, np.float64(0.0)), (305, np.float64(0.0)), (306, np.float64(0.0)), (307, np.float64(0.0)), (308, np.float64(0.0)), (309, np.float64(0.0)), (310, np.float64(0.0)), (311, np.float64(0.0)), (312, np.float64(0.0)), (313, np.float64(0.0)), (314, np.float64(0.0)), (315, np.float64(0.0)), (316, np.float64(0.0)), (317, np.float64(0.0)), (318, np.float64(0.0)), (319, np.float64(0.0)), (320, np.float64(0.0)), (321, np.float64(0.0)), (322, np.float64(0.0)), (323, np.float64(0.0)), (324, np.float64(0.0)), (325, np.float64(0.0)), (326, np.float64(0.0)), (327, np.float64(0.0)), (328, np.float64(0.0)), (329, np.float64(0.0)), (330, np.float64(0.0)), (331, np.float64(0.0)), (332, np.float64(0.0)), (333, np.float64(0.0)), (334, np.float64(0.0)), (335, np.float64(0.0)), (336, np.float64(0.0)), (337, np.float64(0.0)), (338, np.float64(0.0)), (339, np.float64(0.0)), (340, np.float64(0.0)), (341, np.float64(0.0)), (342, np.float64(0.0)), (343, np.float64(0.0)), (344, np.float64(0.0)), (345, np.float64(0.0)), (346, np.float64(0.0)), (347, np.float64(0.0)), (348, np.float64(0.0)), (349, np.float64(0.0)), (350, np.float64(0.0)), (351, np.float64(0.0)), (352, np.float64(0.0)), (353, np.float64(0.0)), (354, np.float64(0.0)), (355, np.float64(0.0)), (356, np.float64(0.0)), (357, np.float64(0.0)), (358, np.float64(0.0)), (359, np.float64(0.0)), (360, np.float64(0.0)), (361, np.float64(0.0)), (362, np.float64(0.0)), (363, np.float64(0.0)), (364, np.float64(0.0)), (365, np.float64(0.0)), (366, np.float64(0.0)), (367, np.float64(0.0)), (368, np.float64(0.0)), (369, np.float64(0.0)), (370, np.float64(0.0)), (371, np.float64(0.0)), (372, np.float64(0.0)), (373, np.float64(0.0)), (374, np.float64(0.0)), (375, np.float64(0.0)), (376, np.float64(0.0)), (377, np.float64(0.0)), (378, np.float64(0.0)), (379, np.float64(0.0)), (380, np.float64(0.0)), (381, np.float64(0.0)), (382, np.float64(0.0)), (383, np.float64(0.0)), (384, np.float64(0.0)), (385, np.float64(0.0)), (386, np.float64(0.0)), (387, np.float64(0.0)), (388, np.float64(0.0)), (389, np.float64(0.0)), (390, np.float64(0.0)), (391, np.float64(0.0)), (392, np.float64(0.0)), (393, np.float64(0.0)), (394, np.float64(0.0)), (395, np.float64(0.0)), (396, np.float64(0.0)), (397, np.float64(0.0)), (398, np.float64(0.0)), (399, np.float64(0.0)), (400, np.float64(0.0)), (401, np.float64(0.0)), (402, np.float64(0.0)), (403, np.float64(0.0)), (404, np.float64(0.0)), (405, np.float64(0.0)), (406, np.float64(0.0)), (407, np.float64(0.0)), (408, np.float64(0.0)), (409, np.float64(0.0)), (410, np.float64(0.0)), (411, np.float64(0.0)), (412, np.float64(0.0)), (413, np.float64(0.0)), (414, np.float64(0.0)), (415, np.float64(0.0)), (416, np.float64(0.0)), (417, np.float64(0.0)), (418, np.float64(0.0)), (419, np.float64(0.0)), (420, np.float64(0.0)), (421, np.float64(0.0)), (422, np.float64(0.0)), (423, np.float64(0.0)), (424, np.float64(0.0)), (425, np.float64(0.0)), (426, np.float64(0.0)), (427, np.float64(0.0)), (428, np.float64(0.0)), (429, np.float64(0.0)), (430, np.float64(0.0)), (431, np.float64(0.0)), (432, np.float64(0.0)), (433, np.float64(0.0)), (434, np.float64(0.0)), (435, np.float64(0.0)), (436, np.float64(0.0)), (437, np.float64(0.0)), (438, np.float64(0.0)), (439, np.float64(0.0)), (440, np.float64(0.0)), (441, np.float64(0.0)), (442, np.float64(0.0)), (443, np.float64(0.0)), (444, np.float64(0.0)), (445, np.float64(0.0)), (446, np.float64(0.0)), (447, np.float64(0.0)), (448, np.float64(0.0)), (449, np.float64(0.0)), (450, np.float64(0.0)), (451, np.float64(0.0)), (452, np.float64(0.0)), (453, np.float64(0.0)), (454, np.float64(0.0)), (455, np.float64(0.0)), (456, np.float64(0.0)), (457, np.float64(0.0)), (458, np.float64(0.0)), (459, np.float64(0.0)), (460, np.float64(0.0)), (461, np.float64(0.0)), (462, np.float64(0.0)), (463, np.float64(0.0)), (464, np.float64(0.0)), (465, np.float64(0.0)), (466, np.float64(0.0)), (467, np.float64(0.0)), (468, np.float64(0.0)), (469, np.float64(0.0)), (470, np.float64(0.0)), (471, np.float64(0.0)), (472, np.float64(0.0)), (473, np.float64(0.0)), (474, np.float64(0.0)), (475, np.float64(0.0)), (476, np.float64(0.0)), (477, np.float64(0.0)), (478, np.float64(0.0)), (479, np.float64(0.0)), (480, np.float64(0.0)), (481, np.float64(0.0)), (482, np.float64(0.0)), (483, np.float64(0.0)), (484, np.float64(0.0)), (485, np.float64(0.0)), (486, np.float64(0.0)), (487, np.float64(0.0)), (488, np.float64(0.0)), (489, np.float64(0.0)), (490, np.float64(0.0)), (491, np.float64(0.0)), (492, np.float64(0.0)), (493, np.float64(0.0)), (494, np.float64(0.0)), (495, np.float64(0.0)), (496, np.float64(0.0)), (497, np.float64(0.0)), (498, np.float64(0.0)), (499, np.float64(0.0)), (500, np.float64(0.0)), (501, np.float64(0.0)), (502, np.float64(0.0)), (503, np.float64(0.0)), (504, np.float64(0.0)), (505, np.float64(0.0)), (506, np.float64(0.0)), (507, np.float64(0.0)), (508, np.float64(0.0)), (509, np.float64(0.0)), (510, np.float64(0.0)), (511, np.float64(0.0)), (512, np.float64(0.0)), (513, np.float64(0.0)), (514, np.float64(0.0)), (515, np.float64(0.0)), (516, np.float64(0.0)), (517, np.float64(0.0)), (518, np.float64(0.0)), (519, np.float64(0.0)), (520, np.float64(0.0)), (521, np.float64(0.0)), (522, np.float64(0.0)), (523, np.float64(0.0)), (524, np.float64(0.0)), (525, np.float64(0.0)), (526, np.float64(0.0)), (527, np.float64(0.0)), (528, np.float64(0.0)), (529, np.float64(0.0)), (530, np.float64(0.0)), (531, np.float64(0.0)), (532, np.float64(0.0)), (533, np.float64(0.0)), (534, np.float64(0.0)), (535, np.float64(0.0)), (536, np.float64(0.0)), (537, np.float64(0.0)), (538, np.float64(0.0)), (539, np.float64(0.0)), (540, np.float64(0.0)), (541, np.float64(0.0)), (542, np.float64(0.0)), (543, np.float64(0.0)), (544, np.float64(0.0)), (545, np.float64(0.0)), (546, np.float64(0.0)), (547, np.float64(0.0)), (548, np.float64(0.0)), (549, np.float64(0.0)), (550, np.float64(0.0)), (551, np.float64(0.0)), (552, np.float64(0.0)), (553, np.float64(0.0)), (554, np.float64(0.0)), (555, np.float64(0.0)), (556, np.float64(0.0)), (557, np.float64(0.0)), (558, np.float64(0.0)), (559, np.float64(0.0)), (560, np.float64(0.0)), (561, np.float64(0.0)), (562, np.float64(0.0)), (563, np.float64(0.0)), (564, np.float64(0.0)), (565, np.float64(0.0)), (566, np.float64(0.0)), (567, np.float64(0.0)), (568, np.float64(0.0)), (569, np.float64(0.0)), (570, np.float64(0.0)), (571, np.float64(0.0)), (572, np.float64(0.0)), (573, np.float64(0.0)), (574, np.float64(0.0)), (575, np.float64(0.0)), (576, np.float64(0.0)), (577, np.float64(0.0)), (578, np.float64(0.0)), (579, np.float64(0.0)), (580, np.float64(0.0)), (581, np.float64(0.0)), (582, np.float64(0.0)), (583, np.float64(0.0)), (584, np.float64(0.0)), (585, np.float64(0.0)), (586, np.float64(0.0)), (587, np.float64(0.0)), (588, np.float64(0.0)), (589, np.float64(0.0)), (590, np.float64(0.0)), (591, np.float64(0.0)), (592, np.float64(0.0)), (593, np.float64(0.0)), (594, np.float64(0.0)), (595, np.float64(0.0)), (596, np.float64(0.0)), (597, np.float64(0.0)), (598, np.float64(0.0)), (599, np.float64(0.0)), (600, np.float64(0.0)), (601, np.float64(0.0)), (602, np.float64(0.0)), (603, np.float64(0.0)), (604, np.float64(0.0)), (605, np.float64(0.0)), (606, np.float64(0.0)), (607, np.float64(0.0)), (608, np.float64(0.0)), (609, np.float64(0.0)), (610, np.float64(0.0)), (611, np.float64(0.0)), (612, np.float64(0.0)), (613, np.float64(0.0)), (614, np.float64(0.0)), (615, np.float64(0.0)), (616, np.float64(0.0)), (617, np.float64(0.0)), (618, np.float64(0.0)), (619, np.float64(0.0)), (620, np.float64(0.0)), (621, np.float64(0.0)), (622, np.float64(0.0)), (623, np.float64(0.0)), (624, np.float64(0.0)), (625, np.float64(0.0)), (626, np.float64(0.0)), (627, np.float64(0.0)), (628, np.float64(0.0)), (629, np.float64(0.0)), (630, np.float64(0.0)), (631, np.float64(0.0)), (632, np.float64(0.0)), (633, np.float64(0.0)), (634, np.float64(0.0)), (635, np.float64(0.0)), (636, np.float64(0.0)), (637, np.float64(0.0)), (638, np.float64(0.0)), (639, np.float64(0.0)), (640, np.float64(0.0)), (641, np.float64(0.0)), (642, np.float64(0.0)), (643, np.float64(0.0)), (644, np.float64(0.0)), (645, np.float64(0.0)), (646, np.float64(0.0)), (647, np.float64(0.0)), (648, np.float64(0.0)), (649, np.float64(0.0)), (650, np.float64(0.0)), (651, np.float64(0.0)), (652, np.float64(0.0)), (653, np.float64(0.0)), (654, np.float64(0.0)), (655, np.float64(0.0)), (656, np.float64(0.0)), (657, np.float64(0.0)), (658, np.float64(0.0)), (659, np.float64(0.0)), (660, np.float64(0.0)), (661, np.float64(0.0)), (662, np.float64(0.0)), (663, np.float64(0.0)), (664, np.float64(0.0)), (665, np.float64(0.0)), (666, np.float64(0.0)), (667, np.float64(0.0)), (668, np.float64(0.0)), (669, np.float64(0.0)), (670, np.float64(0.0)), (671, np.float64(0.0)), (672, np.float64(0.0)), (673, np.float64(0.0)), (674, np.float64(0.0)), (675, np.float64(0.0)), (676, np.float64(0.0)), (677, np.float64(0.0)), (678, np.float64(0.0)), (679, np.float64(0.0)), (680, np.float64(0.0)), (681, np.float64(0.0)), (682, np.float64(0.0)), (683, np.float64(0.0)), (684, np.float64(0.0)), (685, np.float64(0.0)), (686, np.float64(0.0)), (687, np.float64(0.0)), (688, np.float64(0.0)), (689, np.float64(0.0)), (690, np.float64(0.0)), (691, np.float64(0.0)), (692, np.float64(0.0)), (693, np.float64(0.0)), (694, np.float64(0.0)), (695, np.float64(0.0)), (696, np.float64(0.0)), (697, np.float64(0.0)), (698, np.float64(0.0)), (699, np.float64(0.0)), (700, np.float64(0.0)), (701, np.float64(0.0)), (702, np.float64(0.0)), (703, np.float64(0.0)), (704, np.float64(0.0)), (705, np.float64(0.0)), (706, np.float64(0.0)), (707, np.float64(0.0)), (708, np.float64(0.0)), (709, np.float64(0.0)), (710, np.float64(0.0)), (711, np.float64(0.0)), (712, np.float64(0.0)), (713, np.float64(0.0)), (714, np.float64(0.0)), (715, np.float64(0.0)), (716, np.float64(0.0)), (717, np.float64(0.0)), (718, np.float64(0.0)), (719, np.float64(0.0)), (720, np.float64(0.0)), (721, np.float64(0.0)), (722, np.float64(0.0)), (723, np.float64(0.0)), (724, np.float64(0.0)), (725, np.float64(0.0)), (726, np.float64(0.0)), (727, np.float64(0.0)), (728, np.float64(0.0)), (729, np.float64(0.0)), (730, np.float64(0.0)), (731, np.float64(0.0)), (732, np.float64(0.0)), (733, np.float64(0.0)), (734, np.float64(0.0)), (735, np.float64(0.0)), (736, np.float64(0.0)), (737, np.float64(0.0)), (738, np.float64(0.0)), (739, np.float64(0.0)), (740, np.float64(0.0)), (741, np.float64(0.0)), (742, np.float64(0.0)), (743, np.float64(0.0)), (744, np.float64(0.0)), (745, np.float64(0.0)), (746, np.float64(0.0)), (747, np.float64(0.0)), (748, np.float64(0.0)), (749, np.float64(0.0)), (750, np.float64(0.0)), (751, np.float64(0.0)), (752, np.float64(0.0)), (753, np.float64(0.0)), (754, np.float64(0.0)), (755, np.float64(0.0)), (756, np.float64(0.0)), (757, np.float64(0.0)), (758, np.float64(0.0)), (759, np.float64(0.0)), (760, np.float64(0.0)), (761, np.float64(0.0)), (762, np.float64(0.0)), (763, np.float64(0.0)), (764, np.float64(0.0)), (765, np.float64(0.0)), (766, np.float64(0.0)), (767, np.float64(0.0)), (768, np.float64(0.0)), (769, np.float64(0.0)), (770, np.float64(0.0)), (771, np.float64(0.0)), (772, np.float64(0.0)), (773, np.float64(0.0)), (774, np.float64(0.0)), (775, np.float64(0.0)), (776, np.float64(0.0)), (777, np.float64(0.0)), (778, np.float64(0.0)), (779, np.float64(0.0)), (780, np.float64(0.0)), (781, np.float64(0.0)), (782, np.float64(0.0)), (783, np.float64(0.0)), (784, np.float64(0.0)), (785, np.float64(0.0)), (786, np.float64(0.0)), (787, np.float64(0.0)), (788, np.float64(0.0)), (789, np.float64(0.0)), (790, np.float64(0.0)), (791, np.float64(0.0)), (792, np.float64(0.0)), (793, np.float64(0.0)), (794, np.float64(0.0)), (795, np.float64(0.0)), (796, np.float64(0.0)), (797, np.float64(0.0)), (798, np.float64(0.0)), (799, np.float64(0.0)), (800, np.float64(0.0)), (801, np.float64(0.0)), (802, np.float64(0.0)), (803, np.float64(0.0)), (804, np.float64(0.0)), (805, np.float64(0.0)), (806, np.float64(0.0)), (807, np.float64(0.0)), (808, np.float64(0.0)), (809, np.float64(0.0)), (810, np.float64(0.0)), (811, np.float64(0.0)), (812, np.float64(0.0)), (813, np.float64(0.0)), (814, np.float64(0.0)), (815, np.float64(0.0)), (816, np.float64(0.0)), (817, np.float64(0.0)), (818, np.float64(0.0)), (819, np.float64(0.0)), (820, np.float64(0.0)), (821, np.float64(0.0)), (822, np.float64(0.0)), (823, np.float64(0.0)), (824, np.float64(0.0)), (825, np.float64(0.0)), (826, np.float64(0.0)), (827, np.float64(0.0)), (828, np.float64(0.0)), (829, np.float64(0.0)), (830, np.float64(0.0)), (831, np.float64(0.0)), (832, np.float64(0.0)), (833, np.float64(0.0)), (834, np.float64(0.0)), (835, np.float64(0.0)), (836, np.float64(0.0)), (837, np.float64(0.0)

In [31]:
len(Recommendation_Score)

4760

Get all the movies based on Recommendation Score

In [32]:
Sorted_Similar_Movies= sorted(Recommendation_Score, key= lambda x:x[1], reverse= True)
print(Sorted_Similar_Movies)

[(2851, np.float64(1.0000000000000002)), (0, np.float64(0.0)), (1, np.float64(0.0)), (2, np.float64(0.0)), (3, np.float64(0.0)), (4, np.float64(0.0)), (5, np.float64(0.0)), (6, np.float64(0.0)), (7, np.float64(0.0)), (8, np.float64(0.0)), (9, np.float64(0.0)), (10, np.float64(0.0)), (11, np.float64(0.0)), (12, np.float64(0.0)), (13, np.float64(0.0)), (14, np.float64(0.0)), (15, np.float64(0.0)), (16, np.float64(0.0)), (17, np.float64(0.0)), (18, np.float64(0.0)), (19, np.float64(0.0)), (20, np.float64(0.0)), (21, np.float64(0.0)), (22, np.float64(0.0)), (23, np.float64(0.0)), (24, np.float64(0.0)), (25, np.float64(0.0)), (26, np.float64(0.0)), (27, np.float64(0.0)), (28, np.float64(0.0)), (29, np.float64(0.0)), (30, np.float64(0.0)), (31, np.float64(0.0)), (32, np.float64(0.0)), (33, np.float64(0.0)), (34, np.float64(0.0)), (35, np.float64(0.0)), (36, np.float64(0.0)), (37, np.float64(0.0)), (38, np.float64(0.0)), (39, np.float64(0.0)), (40, np.float64(0.0)), (41, np.float64(0.0)), (42, np.float64(0.0)), (43, np.float64(0.0)), (44, np.float64(0.0)), (45, np.float64(0.0)), (46, np.float64(0.0)), (47, np.float64(0.0)), (48, np.float64(0.0)), (49, np.float64(0.0)), (50, np.float64(0.0)), (51, np.float64(0.0)), (52, np.float64(0.0)), (53, np.float64(0.0)), (54, np.float64(0.0)), (55, np.float64(0.0)), (56, np.float64(0.0)), (57, np.float64(0.0)), (58, np.float64(0.0)), (59, np.float64(0.0)), (60, np.float64(0.0)), (61, np.float64(0.0)), (62, np.float64(0.0)), (63, np.float64(0.0)), (64, np.float64(0.0)), (65, np.float64(0.0)), (66, np.float64(0.0)), (67, np.float64(0.0)), (68, np.float64(0.0)), (69, np.float64(0.0)), (70, np.float64(0.0)), (71, np.float64(0.0)), (72, np.float64(0.0)), (73, np.float64(0.0)), (74, np.float64(0.0)), (75, np.float64(0.0)), (76, np.float64(0.0)), (77, np.float64(0.0)), (78, np.float64(0.0)), (79, np.float64(0.0)), (80, np.float64(0.0)), (81, np.float64(0.0)), (82, np.float64(0.0)), (83, np.float64(0.0)), (84, np.float64(0.0)), (85, np.float64(0.0)), (86, np.float64(0.0)), (87, np.float64(0.0)), (88, np.float64(0.0)), (89, np.float64(0.0)), (90, np.float64(0.0)), (91, np.float64(0.0)), (92, np.float64(0.0)), (93, np.float64(0.0)), (94, np.float64(0.0)), (95, np.float64(0.0)), (96, np.float64(0.0)), (97, np.float64(0.0)), (98, np.float64(0.0)), (99, np.float64(0.0)), (100, np.float64(0.0)), (101, np.float64(0.0)), (102, np.float64(0.0)), (103, np.float64(0.0)), (104, np.float64(0.0)), (105, np.float64(0.0)), (106, np.float64(0.0)), (107, np.float64(0.0)), (108, np.float64(0.0)), (109, np.float64(0.0)), (110, np.float64(0.0)), (111, np.float64(0.0)), (112, np.float64(0.0)), (113, np.float64(0.0)), (114, np.float64(0.0)), (115, np.float64(0.0)), (116, np.float64(0.0)), (117, np.float64(0.0)), (118, np.float64(0.0)), (119, np.float64(0.0)), (120, np.float64(0.0)), (121, np.float64(0.0)), (122, np.float64(0.0)), (123, np.float64(0.0)), (124, np.float64(0.0)), (125, np.float64(0.0)), (126, np.float64(0.0)), (127, np.float64(0.0)), (128, np.float64(0.0)), (129, np.float64(0.0)), (130, np.float64(0.0)), (131, np.float64(0.0)), (132, np.float64(0.0)), (133, np.float64(0.0)), (134, np.float64(0.0)), (135, np.float64(0.0)), (136, np.float64(0.0)), (137, np.float64(0.0)), (138, np.float64(0.0)), (139, np.float64(0.0)), (140, np.float64(0.0)), (141, np.float64(0.0)), (142, np.float64(0.0)), (143, np.float64(0.0)), (144, np.float64(0.0)), (145, np.float64(0.0)), (146, np.float64(0.0)), (147, np.float64(0.0)), (148, np.float64(0.0)), (149, np.float64(0.0)), (150, np.float64(0.0)), (151, np.float64(0.0)), (152, np.float64(0.0)), (153, np.float64(0.0)), (154, np.float64(0.0)), (155, np.float64(0.0)), (156, np.float64(0.0)), (157, np.float64(0.0)), (158, np.float64(0.0)), (159, np.float64(0.0)), (160, np.float64(0.0)), (161, np.float64(0.0)), (162, np.float64(0.0)), (163, np.float64(0.0)), (164, np.float64(0.0)), (165, np.float64(0.0)), (166, np.float64(0.0)), (167, np.float64(0.0)), (168, np.float64(0.0)), (169, np.float64(0.0)), (170, np.float64(0.0)), (171, np.float64(0.0)), (172, np.float64(0.0)), (173, np.float64(0.0)), (174, np.float64(0.0)), (175, np.float64(0.0)), (176, np.float64(0.0)), (177, np.float64(0.0)), (178, np.float64(0.0)), (179, np.float64(0.0)), (180, np.float64(0.0)), (181, np.float64(0.0)), (182, np.float64(0.0)), (183, np.float64(0.0)), (184, np.float64(0.0)), (185, np.float64(0.0)), (186, np.float64(0.0)), (187, np.float64(0.0)), (188, np.float64(0.0)), (189, np.float64(0.0)), (190, np.float64(0.0)), (191, np.float64(0.0)), (192, np.float64(0.0)), (193, np.float64(0.0)), (194, np.float64(0.0)), (195, np.float64(0.0)), (196, np.float64(0.0)), (197, np.float64(0.0)), (198, np.float64(0.0)), (199, np.float64(0.0)), (200, np.float64(0.0)), (201, np.float64(0.0)), (202, np.float64(0.0)), (203, np.float64(0.0)), (204, np.float64(0.0)), (205, np.float64(0.0)), (206, np.float64(0.0)), (207, np.float64(0.0)), (208, np.float64(0.0)), (209, np.float64(0.0)), (210, np.float64(0.0)), (211, np.float64(0.0)), (212, np.float64(0.0)), (213, np.float64(0.0)), (214, np.float64(0.0)), (215, np.float64(0.0)), (216, np.float64(0.0)), (217, np.float64(0.0)), (218, np.float64(0.0)), (219, np.float64(0.0)), (220, np.float64(0.0)), (221, np.float64(0.0)), (222, np.float64(0.0)), (223, np.float64(0.0)), (224, np.float64(0.0)), (225, np.float64(0.0)), (226, np.float64(0.0)), (227, np.float64(0.0)), (228, np.float64(0.0)), (229, np.float64(0.0)), (230, np.float64(0.0)), (231, np.float64(0.0)), (232, np.float64(0.0)), (233, np.float64(0.0)), (234, np.float64(0.0)), (235, np.float64(0.0)), (236, np.float64(0.0)), (237, np.float64(0.0)), (238, np.float64(0.0)), (239, np.float64(0.0)), (240, np.float64(0.0)), (241, np.float64(0.0)), (242, np.float64(0.0)), (243, np.float64(0.0)), (244, np.float64(0.0)), (245, np.float64(0.0)), (246, np.float64(0.0)), (247, np.float64(0.0)), (248, np.float64(0.0)), (249, np.float64(0.0)), (250, np.float64(0.0)), (251, np.float64(0.0)), (252, np.float64(0.0)), (253, np.float64(0.0)), (254, np.float64(0.0)), (255, np.float64(0.0)), (256, np.float64(0.0)), (257, np.float64(0.0)), (258, np.float64(0.0)), (259, np.float64(0.0)), (260, np.float64(0.0)), (261, np.float64(0.0)), (262, np.float64(0.0)), (263, np.float64(0.0)), (264, np.float64(0.0)), (265, np.float64(0.0)), (266, np.float64(0.0)), (267, np.float64(0.0)), (268, np.float64(0.0)), (269, np.float64(0.0)), (270, np.float64(0.0)), (271, np.float64(0.0)), (272, np.float64(0.0)), (273, np.float64(0.0)), (274, np.float64(0.0)), (275, np.float64(0.0)), (276, np.float64(0.0)), (277, np.float64(0.0)), (278, np.float64(0.0)), (279, np.float64(0.0)), (280, np.float64(0.0)), (281, np.float64(0.0)), (282, np.float64(0.0)), (283, np.float64(0.0)), (284, np.float64(0.0)), (285, np.float64(0.0)), (286, np.float64(0.0)), (287, np.float64(0.0)), (288, np.float64(0.0)), (289, np.float64(0.0)), (290, np.float64(0.0)), (291, np.float64(0.0)), (292, np.float64(0.0)), (293, np.float64(0.0)), (294, np.float64(0.0)), (295, np.float64(0.0)), (296, np.float64(0.0)), (297, np.float64(0.0)), (298, np.float64(0.0)), (299, np.float64(0.0)), (300, np.float64(0.0)), (301, np.float64(0.0)), (302, np.float64(0.0)), (303, np.float64(0.0)), (304, np.float64(0.0)), (305, np.float64(0.0)), (306, np.float64(0.0)), (307, np.float64(0.0)), (308, np.float64(0.0)), (309, np.float64(0.0)), (310, np.float64(0.0)), (311, np.float64(0.0)), (312, np.float64(0.0)), (313, np.float64(0.0)), (314, np.float64(0.0)), (315, np.float64(0.0)), (316, np.float64(0.0)), (317, np.float64(0.0)), (318, np.float64(0.0)), (319, np.float64(0.0)), (320, np.float64(0.0)), (321, np.float64(0.0)), (322, np.float64(0.0)), (323, np.float64(0.0)), (324, np.float64(0.0)), (325, np.float64(0.0)), (326, np.float64(0.0)), (327, np.float64(0.0)), (328, np.float64(0.0)), (329, np.float64(0.0)), (330, np.float64(0.0)), (331, np.float64(0.0)), (332, np.float64(0.0)), (333, np.float64(0.0)), (334, np.float64(0.0)), (335, np.float64(0.0)), (336, np.float64(0.0)), (337, np.float64(0.0)), (338, np.float64(0.0)), (339, np.float64(0.0)), (340, np.float64(0.0)), (341, np.float64(0.0)), (342, np.float64(0.0)), (343, np.float64(0.0)), (344, np.float64(0.0)), (345, np.float64(0.0)), (346, np.float64(0.0)), (347, np.float64(0.0)), (348, np.float64(0.0)), (349, np.float64(0.0)), (350, np.float64(0.0)), (351, np.float64(0.0)), (352, np.float64(0.0)), (353, np.float64(0.0)), (354, np.float64(0.0)), (355, np.float64(0.0)), (356, np.float64(0.0)), (357, np.float64(0.0)), (358, np.float64(0.0)), (359, np.float64(0.0)), (360, np.float64(0.0)), (361, np.float64(0.0)), (362, np.float64(0.0)), (363, np.float64(0.0)), (364, np.float64(0.0)), (365, np.float64(0.0)), (366, np.float64(0.0)), (367, np.float64(0.0)), (368, np.float64(0.0)), (369, np.float64(0.0)), (370, np.float64(0.0)), (371, np.float64(0.0)), (372, np.float64(0.0)), (373, np.float64(0.0)), (374, np.float64(0.0)), (375, np.float64(0.0)), (376, np.float64(0.0)), (377, np.float64(0.0)), (378, np.float64(0.0)), (379, np.float64(0.0)), (380, np.float64(0.0)), (381, np.float64(0.0)), (382, np.float64(0.0)), (383, np.float64(0.0)), (384, np.float64(0.0)), (385, np.float64(0.0)), (386, np.float64(0.0)), (387, np.float64(0.0)), (388, np.float64(0.0)), (389, np.float64(0.0)), (390, np.float64(0.0)), (391, np.float64(0.0)), (392, np.float64(0.0)), (393, np.float64(0.0)), (394, np.float64(0.0)), (395, np.float64(0.0)), (396, np.float64(0.0)), (397, np.float64(0.0)), (398, np.float64(0.0)), (399, np.float64(0.0)), (400, np.float64(0.0)), (401, np.float64(0.0)), (402, np.float64(0.0)), (403, np.float64(0.0)), (404, np.float64(0.0)), (405, np.float64(0.0)), (406, np.float64(0.0)), (407, np.float64(0.0)), (408, np.float64(0.0)), (409, np.float64(0.0)), (410, np.float64(0.0)), (411, np.float64(0.0)), (412, np.float64(0.0)), (413, np.float64(0.0)), (414, np.float64(0.0)), (415, np.float64(0.0)), (416, np.float64(0.0)), (417, np.float64(0.0)), (418, np.float64(0.0)), (419, np.float64(0.0)), (420, np.float64(0.0)), (421, np.float64(0.0)), (422, np.float64(0.0)), (423, np.float64(0.0)), (424, np.float64(0.0)), (425, np.float64(0.0)), (426, np.float64(0.0)), (427, np.float64(0.0)), (428, np.float64(0.0)), (429, np.float64(0.0)), (430, np.float64(0.0)), (431, np.float64(0.0)), (432, np.float64(0.0)), (433, np.float64(0.0)), (434, np.float64(0.0)), (435, np.float64(0.0)), (436, np.float64(0.0)), (437, np.float64(0.0)), (438, np.float64(0.0)), (439, np.float64(0.0)), (440, np.float64(0.0)), (441, np.float64(0.0)), (442, np.float64(0.0)), (443, np.float64(0.0)), (444, np.float64(0.0)), (445, np.float64(0.0)), (446, np.float64(0.0)), (447, np.float64(0.0)), (448, np.float64(0.0)), (449, np.float64(0.0)), (450, np.float64(0.0)), (451, np.float64(0.0)), (452, np.float64(0.0)), (453, np.float64(0.0)), (454, np.float64(0.0)), (455, np.float64(0.0)), (456, np.float64(0.0)), (457, np.float64(0.0)), (458, np.float64(0.0)), (459, np.float64(0.0)), (460, np.float64(0.0)), (461, np.float64(0.0)), (462, np.float64(0.0)), (463, np.float64(0.0)), (464, np.float64(0.0)), (465, np.float64(0.0)), (466, np.float64(0.0)), (467, np.float64(0.0)), (468, np.float64(0.0)), (469, np.float64(0.0)), (470, np.float64(0.0)), (471, np.float64(0.0)), (472, np.float64(0.0)), (473, np.float64(0.0)), (474, np.float64(0.0)), (475, np.float64(0.0)), (476, np.float64(0.0)), (477, np.float64(0.0)), (478, np.float64(0.0)), (479, np.float64(0.0)), (480, np.float64(0.0)), (481, np.float64(0.0)), (482, np.float64(0.0)), (483, np.float64(0.0)), (484, np.float64(0.0)), (485, np.float64(0.0)), (486, np.float64(0.0)), (487, np.float64(0.0)), (488, np.float64(0.0)), (489, np.float64(0.0)), (490, np.float64(0.0)), (491, np.float64(0.0)), (492, np.float64(0.0)), (493, np.float64(0.0)), (494, np.float64(0.0)), (495, np.float64(0.0)), (496, np.float64(0.0)), (497, np.float64(0.0)), (498, np.float64(0.0)), (499, np.float64(0.0)), (500, np.float64(0.0)), (501, np.float64(0.0)), (502, np.float64(0.0)), (503, np.float64(0.0)), (504, np.float64(0.0)), (505, np.float64(0.0)), (506, np.float64(0.0)), (507, np.float64(0.0)), (508, np.float64(0.0)), (509, np.float64(0.0)), (510, np.float64(0.0)), (511, np.float64(0.0)), (512, np.float64(0.0)), (513, np.float64(0.0)), (514, np.float64(0.0)), (515, np.float64(0.0)), (516, np.float64(0.0)), (517, np.float64(0.0)), (518, np.float64(0.0)), (519, np.float64(0.0)), (520, np.float64(0.0)), (521, np.float64(0.0)), (522, np.float64(0.0)), (523, np.float64(0.0)), (524, np.float64(0.0)), (525, np.float64(0.0)), (526, np.float64(0.0)), (527, np.float64(0.0)), (528, np.float64(0.0)), (529, np.float64(0.0)), (530, np.float64(0.0)), (531, np.float64(0.0)), (532, np.float64(0.0)), (533, np.float64(0.0)), (534, np.float64(0.0)), (535, np.float64(0.0)), (536, np.float64(0.0)), (537, np.float64(0.0)), (538, np.float64(0.0)), (539, np.float64(0.0)), (540, np.float64(0.0)), (541, np.float64(0.0)), (542, np.float64(0.0)), (543, np.float64(0.0)), (544, np.float64(0.0)), (545, np.float64(0.0)), (546, np.float64(0.0)), (547, np.float64(0.0)), (548, np.float64(0.0)), (549, np.float64(0.0)), (550, np.float64(0.0)), (551, np.float64(0.0)), (552, np.float64(0.0)), (553, np.float64(0.0)), (554, np.float64(0.0)), (555, np.float64(0.0)), (556, np.float64(0.0)), (557, np.float64(0.0)), (558, np.float64(0.0)), (559, np.float64(0.0)), (560, np.float64(0.0)), (561, np.float64(0.0)), (562, np.float64(0.0)), (563, np.float64(0.0)), (564, np.float64(0.0)), (565, np.float64(0.0)), (566, np.float64(0.0)), (567, np.float64(0.0)), (568, np.float64(0.0)), (569, np.float64(0.0)), (570, np.float64(0.0)), (571, np.float64(0.0)), (572, np.float64(0.0)), (573, np.float64(0.0)), (574, np.float64(0.0)), (575, np.float64(0.0)), (576, np.float64(0.0)), (577, np.float64(0.0)), (578, np.float64(0.0)), (579, np.float64(0.0)), (580, np.float64(0.0)), (581, np.float64(0.0)), (582, np.float64(0.0)), (583, np.float64(0.0)), (584, np.float64(0.0)), (585, np.float64(0.0)), (586, np.float64(0.0)), (587, np.float64(0.0)), (588, np.float64(0.0)), (589, np.float64(0.0)), (590, np.float64(0.0)), (591, np.float64(0.0)), (592, np.float64(0.0)), (593, np.float64(0.0)), (594, np.float64(0.0)), (595, np.float64(0.0)), (596, np.float64(0.0)), (597, np.float64(0.0)), (598, np.float64(0.0)), (599, np.float64(0.0)), (600, np.float64(0.0)), (601, np.float64(0.0)), (602, np.float64(0.0)), (603, np.float64(0.0)), (604, np.float64(0.0)), (605, np.float64(0.0)), (606, np.float64(0.0)), (607, np.float64(0.0)), (608, np.float64(0.0)), (609, np.float64(0.0)), (610, np.float64(0.0)), (611, np.float64(0.0)), (612, np.float64(0.0)), (613, np.float64(0.0)), (614, np.float64(0.0)), (615, np.float64(0.0)), (616, np.float64(0.0)), (617, np.float64(0.0)), (618, np.float64(0.0)), (619, np.float64(0.0)), (620, np.float64(0.0)), (621, np.float64(0.0)), (622, np.float64(0.0)), (623, np.float64(0.0)), (624, np.float64(0.0)), (625, np.float64(0.0)), (626, np.float64(0.0)), (627, np.float64(0.0)), (628, np.float64(0.0)), (629, np.float64(0.0)), (630, np.float64(0.0)), (631, np.float64(0.0)), (632, np.float64(0.0)), (633, np.float64(0.0)), (634, np.float64(0.0)), (635, np.float64(0.0)), (636, np.float64(0.0)), (637, np.float64(0.0)), (638, np.float64(0.0)), (639, np.float64(0.0)), (640, np.float64(0.0)), (641, np.float64(0.0)), (642, np.float64(0.0)), (643, np.float64(0.0)), (644, np.float64(0.0)), (645, np.float64(0.0)), (646, np.float64(0.0)), (647, np.float64(0.0)), (648, np.float64(0.0)), (649, np.float64(0.0)), (650, np.float64(0.0)), (651, np.float64(0.0)), (652, np.float64(0.0)), (653, np.float64(0.0)), (654, np.float64(0.0)), (655, np.float64(0.0)), (656, np.float64(0.0)), (657, np.float64(0.0)), (658, np.float64(0.0)), (659, np.float64(0.0)), (660, np.float64(0.0)), (661, np.float64(0.0)), (662, np.float64(0.0)), (663, np.float64(0.0)), (664, np.float64(0.0)), (665, np.float64(0.0)), (666, np.float64(0.0)), (667, np.float64(0.0)), (668, np.float64(0.0)), (669, np.float64(0.0)), (670, np.float64(0.0)), (671, np.float64(0.0)), (672, np.float64(0.0)), (673, np.float64(0.0)), (674, np.float64(0.0)), (675, np.float64(0.0)), (676, np.float64(0.0)), (677, np.float64(0.0)), (678, np.float64(0.0)), (679, np.float64(0.0)), (680, np.float64(0.0)), (681, np.float64(0.0)), (682, np.float64(0.0)), (683, np.float64(0.0)), (684, np.float64(0.0)), (685, np.float64(0.0)), (686, np.float64(0.0)), (687, np.float64(0.0)), (688, np.float64(0.0)), (689, np.float64(0.0)), (690, np.float64(0.0)), (691, np.float64(0.0)), (692, np.float64(0.0)), (693, np.float64(0.0)), (694, np.float64(0.0)), (695, np.float64(0.0)), (696, np.float64(0.0)), (697, np.float64(0.0)), (698, np.float64(0.0)), (699, np.float64(0.0)), (700, np.float64(0.0)), (701, np.float64(0.0)), (702, np.float64(0.0)), (703, np.float64(0.0)), (704, np.float64(0.0)), (705, np.float64(0.0)), (706, np.float64(0.0)), (707, np.float64(0.0)), (708, np.float64(0.0)), (709, np.float64(0.0)), (710, np.float64(0.0)), (711, np.float64(0.0)), (712, np.float64(0.0)), (713, np.float64(0.0)), (714, np.float64(0.0)), (715, np.float64(0.0)), (716, np.float64(0.0)), (717, np.float64(0.0)), (718, np.float64(0.0)), (719, np.float64(0.0)), (720, np.float64(0.0)), (721, np.float64(0.0)), (722, np.float64(0.0)), (723, np.float64(0.0)), (724, np.float64(0.0)), (725, np.float64(0.0)), (726, np.float64(0.0)), (727, np.float64(0.0)), (728, np.float64(0.0)), (729, np.float64(0.0)), (730, np.float64(0.0)), (731, np.float64(0.0)), (732, np.float64(0.0)), (733, np.float64(0.0)), (734, np.float64(0.0)), (735, np.float64(0.0)), (736, np.float64(0.0)), (737, np.float64(0.0)), (738, np.float64(0.0)), (739, np.float64(0.0)), (740, np.float64(0.0)), (741, np.float64(0.0)), (742, np.float64(0.0)), (743, np.float64(0.0)), (744, np.float64(0.0)), (745, np.float64(0.0)), (746, np.float64(0.0)), (747, np.float64(0.0)), (748, np.float64(0.0)), (749, np.float64(0.0)), (750, np.float64(0.0)), (751, np.float64(0.0)), (752, np.float64(0.0)), (753, np.float64(0.0)), (754, np.float64(0.0)), (755, np.float64(0.0)), (756, np.float64(0.0)), (757, np.float64(0.0)), (758, np.float64(0.0)), (759, np.float64(0.0)), (760, np.float64(0.0)), (761, np.float64(0.0)), (762, np.float64(0.0)), (763, np.float64(0.0)), (764, np.float64(0.0)), (765, np.float64(0.0)), (766, np.float64(0.0)), (767, np.float64(0.0)), (768, np.float64(0.0)), (769, np.float64(0.0)), (770, np.float64(0.0)), (771, np.float64(0.0)), (772, np.float64(0.0)), (773, np.float64(0.0)), (774, np.float64(0.0)), (775, np.float64(0.0)), (776, np.float64(0.0)), (777, np.float64(0.0)), (778, np.float64(0.0)), (779, np.float64(0.0)), (780, np.float64(0.0)), (781, np.float64(0.0)), (782, np.float64(0.0)), (783, np.float64(0.0)), (784, np.float64(0.0)), (785, np.float64(0.0)), (786, np.float64(0.0)), (787, np.float64(0.0)), (788, np.float64(0.0)), (789, np.float64(0.0)), (790, np.float64(0.0)), (791, np.float64(0.0)), (792, np.float64(0.0)), (793, np.float64(0.0)), (794, np.float64(0.0)), (795, np.float64(0.0)), (796, np.float64(0.0)), (797, np.float64(0.0)), (798, np.float64(0.0)), (799, np.float64(0.0)), (800, np.float64(0.0)), (801, np.float64(0.0)), (802, np.float64(0.0)), (803, np.float64(0.0)), (804, np.float64(0.0)), (805, np.float64(0.0)), (806, np.float64(0.0)), (807, np.float64(0.0)), (808, np.float64(0.0)), (809, np.float64(0.0)), (810, np.float64(0.0)), (811, np.float64(0.0)), (812, np.float64(0.0)), (813, np.float64(0.0)), (814, np.float64(0.0)), (815, np.float64(0.0)), (816, np.float64(0.0)), (817, np.float64(0.0)), (818, np.float64(0.0)), (819, np.float64(0.0)), (820, np.float64(0.0)), (821, np.float64(0.0)), (822, np.float64(0.0)), (823, np.float64(0.0)), (824, np.float64(0.0)), (825, np.float64(0.0)), (826, np.float64(0.0)), (827, np.float64(0.0)), (828, np.float64(0.0)), (829, np.float64(0.0)), (830, np.float64(0.0)), (831, np.float64(0.0)), (832, np.float64(0.0)), (833, np.float64(0.0)), (834, np.float64(0.0)), (835, np.float64(0.0)), (836,

Print the similar movies based on index

In [33]:
print('Top 30 Movies suggested for you: \n')

i=1
for movie in Sorted_Similar_Movies:
  index= movie[0]
  title_from_index= movie[1]
  if (i<31):
    print(i, '.' , movie)
    i+=1

Top 30 Movies suggested for you:

1 . (2851, np.float64(1.0000000000000002))
2 . (0, np.float64(0.0))
3 . (1, np.float64(0.0))
4 . (2, np.float64(0.0))
5 . (3, np.float64(0.0))
6 . (4, np.float64(0.0))
7 . (5, np.float64(0.0))
8 . (6, np.float64(0.0))
9 . (7, np.float64(0.0))
10 . (8, np.float64(0.0))
11 . (9, np.float64(0.0))
12 . (10, np.float64(0.0))
13 . (11, np.float64(0.0))
14 . (12, np.float64(0.0))
15 . (13, np.float64(0.0))
16 . (14, np.float64(0.0))
17 . (15, np.float64(0.0))
18 . (16, np.float64(0.0))
19 . (17, np.float64(0.0))
20 . (18, np.float64(0.0))
21 . (19, np.float64(0.0))
22 . (20, np.float64(0.0))
23 . (21, np.float64(0.0))
24 . (22, np.float64(0.0))
25 . (23, np.float64(0.0))
26 . (24, np.float64(0.0))
27 . (25, np.float64(0.0))
28 . (26, np.float64(0.0))
29 . (27, np.float64(0.0))
30 . (28, np.float64(0.0))

In [34]:
Movie_Name = input(' Enter your favourite movie name : ')

list_of_all_titles = df['Movie_Title'].tolist()

Find_Close_Match = difflib.get_close_matches(Movie_Name, list_of_all_titles)

Close_Match = Find_Close_Match[0]

Index_of_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(Similarity_score[Index_of_Movie]))

sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)

print('Top 10 Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = df[df.Movie_ID == index]['Movie_Title'].values
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Ironman
Top 10 Movies suggested for you :

1 . ['Iron Man']
2 . ['The Imitation Game']
3 . ['The Loss of Sexual Innocence']
4 . ['Ted']
5 . ['Frances Ha']
6 . ['Anaconda']
7 . ['The Geographer Drank His Globe Away']
8 . ['Mortal Kombat']
9 . ['The Book Thief']
10 . ['The Color of Money']